pipeline {
    agent any
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
    }
    stages {
        stage("Welcome!") {
            steps {
                echo "You reached the GitHub Account of Henry-NS-2021."
            }
            steps{
              echo "creating a file..."
              sleep 5
              echo "file generated by a commit on the main branch" > auto_generated.txt
            }
        }
          stage("finishing the job"){
            steps{
              sleep 3
              echo "job finishin in 3 sec"
            }
          }
    }
}
